repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: make test
        language: system
        types: [python]

      - id: run-linters
        name: Run Linters
        entry: make lint
        language: system
        types: [python]

      - id: run-types
        name: Run Types
        entry: make types
        language: system
        types: [python]
